### ISSUE TITLE
Defining functions

### ISSUE THREAD

**Issue by ManuelFay** [illuin-tech/configue#47]
Is it possible to instanciate a Callable function that we pass in the yaml file:
`fn:  my_module.my_function`

If so, can it be documented  a bit more please ?
I ofc can instanciate a class, and override` __call__` to run my function but it seems a bit of a stretch !

Thanks !

**Comment by Aegdesil** [comment]
Yes, it is possible to call a function and get the returned value with the same syntax as the class instantiation
```
fn_result:
  (): my_module.my_function
  arg: my_value
```

I'll update the docs to make it clearer.

**Comment by ManuelFay** [comment]
My bad for the misunderstanding.
I actually wanted for the function not to be instantiated upon config loading - and basically be able to pass the function as an argument to other functions to be used later, by a map function for example.
